platform :ios, '6.1'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'STableViewController'
pod 'ViewDeck'
pod 'SSToolkit'
pod 'XMLReader'
pod 'MHTabBarController', '~> 0.0.1'
pod 'FPPopover'
